const booksData = [
  // ── PROGRAMMING (28 books) ──────────────────────────────
  { id: 1,  title: "Clean Code", author: "Robert C. Martin", price: 599, image: "https://covers.openlibrary.org/b/id/8231996-M.jpg", category: "Programming" },
  { id: 2,  title: "The Pragmatic Programmer", author: "Andrew Hunt", price: 699, image: "https://covers.openlibrary.org/b/id/8231997-M.jpg", category: "Programming" },
  { id: 3,  title: "JavaScript: The Good Parts", author: "Douglas Crockford", price: 449, image: "https://covers.openlibrary.org/b/id/8231998-M.jpg", category: "Programming" },
  { id: 4,  title: "You Don't Know JS", author: "Kyle Simpson", price: 399, image: "https://covers.openlibrary.org/b/id/8231999-M.jpg", category: "Programming" },
  { id: 5,  title: "Python Crash Course", author: "Eric Matthes", price: 499, image: "https://covers.openlibrary.org/b/id/8232000-M.jpg", category: "Programming" },
  { id: 6,  title: "Design Patterns", author: "Gang of Four", price: 749, image: "https://covers.openlibrary.org/b/id/8232001-M.jpg", category: "Programming" },
  { id: 7,  title: "Refactoring", author: "Martin Fowler", price: 649, image: "https://covers.openlibrary.org/b/id/8232002-M.jpg", category: "Programming" },
  { id: 8,  title: "Code Complete", author: "Steve McConnell", price: 799, image: "https://covers.openlibrary.org/b/id/8232003-M.jpg", category: "Programming" },
  { id: 41, title: "Introduction to Algorithms", author: "Cormen & Leiserson", price: 999, image: "https://covers.openlibrary.org/b/id/8232040-M.jpg", category: "Programming" },
  { id: 42, title: "Structure & Interpretation of Programs", author: "Abelson & Sussman", price: 799, image: "https://covers.openlibrary.org/b/id/8232041-M.jpg", category: "Programming" },
  { id: 43, title: "The C Programming Language", author: "Kernighan & Ritchie", price: 549, image: "https://covers.openlibrary.org/b/id/8232042-M.jpg", category: "Programming" },
  { id: 44, title: "Head First Design Patterns", author: "Freeman & Robson", price: 699, image: "https://covers.openlibrary.org/b/id/8232043-M.jpg", category: "Programming" },
  { id: 45, title: "Cracking the Coding Interview", author: "Gayle Laakmann", price: 649, image: "https://covers.openlibrary.org/b/id/8232044-M.jpg", category: "Programming" },
  { id: 46, title: "Eloquent JavaScript", author: "Marijn Haverbeke", price: 499, image: "https://covers.openlibrary.org/b/id/8232045-M.jpg", category: "Programming" },
  { id: 47, title: "Learning Python", author: "Mark Lutz", price: 749, image: "https://covers.openlibrary.org/b/id/8232046-M.jpg", category: "Programming" },
  { id: 48, title: "The Mythical Man-Month", author: "Frederick Brooks", price: 579, image: "https://covers.openlibrary.org/b/id/8232047-M.jpg", category: "Programming" },
  { id: 49, title: "Working with Legacy Code", author: "Michael Feathers", price: 629, image: "https://covers.openlibrary.org/b/id/8232048-M.jpg", category: "Programming" },
  { id: 50, title: "Domain-Driven Design", author: "Eric Evans", price: 799, image: "https://covers.openlibrary.org/b/id/8232049-M.jpg", category: "Programming" },
  { id: 51, title: "Continuous Delivery", author: "Jez Humble", price: 699, image: "https://covers.openlibrary.org/b/id/8232050-M.jpg", category: "Programming" },
  { id: 52, title: "The Art of Computer Programming", author: "Donald Knuth", price: 1199, image: "https://covers.openlibrary.org/b/id/8232051-M.jpg", category: "Programming" },
  { id: 53, title: "Computer Networks", author: "Andrew Tanenbaum", price: 799, image: "https://covers.openlibrary.org/b/id/8232052-M.jpg", category: "Programming" },
  { id: 54, title: "Operating System Concepts", author: "Silberschatz", price: 849, image: "https://covers.openlibrary.org/b/id/8232053-M.jpg", category: "Programming" },
  { id: 55, title: "Database System Concepts", author: "Silberschatz", price: 849, image: "https://covers.openlibrary.org/b/id/8232054-M.jpg", category: "Programming" },
  { id: 56, title: "Compilers: Principles & Tools", author: "Aho, Lam, Sethi", price: 899, image: "https://covers.openlibrary.org/b/id/8232055-M.jpg", category: "Programming" },
  { id: 57, title: "Modern Operating Systems", author: "Andrew Tanenbaum", price: 799, image: "https://covers.openlibrary.org/b/id/8232056-M.jpg", category: "Programming" },
  { id: 58, title: "React Up and Running", author: "Stoyan Stefanov", price: 499, image: "https://covers.openlibrary.org/b/id/8232057-M.jpg", category: "Programming" },
  { id: 59, title: "Node.js Design Patterns", author: "Mario Casciaro", price: 649, image: "https://covers.openlibrary.org/b/id/8232058-M.jpg", category: "Programming" },
  { id: 60, title: "TypeScript Deep Dive", author: "Basarat Ali Syed", price: 449, image: "https://covers.openlibrary.org/b/id/8232059-M.jpg", category: "Programming" },

  // ── ENGINEERING (28 books) ──────────────────────────────
  { id: 9,  title: "Engineering Mathematics", author: "K.A. Stroud", price: 550, image: "https://covers.openlibrary.org/b/id/8232004-M.jpg", category: "Engineering" },
  { id: 10, title: "Thermodynamics", author: "Cengel & Boles", price: 720, image: "https://covers.openlibrary.org/b/id/8232005-M.jpg", category: "Engineering" },
  { id: 11, title: "Fluid Mechanics", author: "Frank White", price: 680, image: "https://covers.openlibrary.org/b/id/8232006-M.jpg", category: "Engineering" },
  { id: 12, title: "Structural Analysis", author: "R.C. Hibbeler", price: 760, image: "https://covers.openlibrary.org/b/id/8232007-M.jpg", category: "Engineering" },
  { id: 13, title: "Control Systems", author: "Norman Nise", price: 610, image: "https://covers.openlibrary.org/b/id/8232008-M.jpg", category: "Engineering" },
  { id: 14, title: "Circuit Analysis", author: "James Nilsson", price: 570, image: "https://covers.openlibrary.org/b/id/8232009-M.jpg", category: "Engineering" },
  { id: 15, title: "Materials Science", author: "William Callister", price: 690, image: "https://covers.openlibrary.org/b/id/8232010-M.jpg", category: "Engineering" },
  { id: 16, title: "Machine Design", author: "Robert Shigley", price: 740, image: "https://covers.openlibrary.org/b/id/8232011-M.jpg", category: "Engineering" },
  { id: 61, title: "Engineering Mechanics: Statics", author: "R.C. Hibbeler", price: 780, image: "https://covers.openlibrary.org/b/id/8232060-M.jpg", category: "Engineering" },
  { id: 62, title: "Engineering Mechanics: Dynamics", author: "R.C. Hibbeler", price: 780, image: "https://covers.openlibrary.org/b/id/8232061-M.jpg", category: "Engineering" },
  { id: 63, title: "Signals and Systems", author: "Oppenheim & Willsky", price: 820, image: "https://covers.openlibrary.org/b/id/8232062-M.jpg", category: "Engineering" },
  { id: 64, title: "Electric Machinery Fundamentals", author: "Stephen Chapman", price: 760, image: "https://covers.openlibrary.org/b/id/8232063-M.jpg", category: "Engineering" },
  { id: 65, title: "Microelectronics Circuit Analysis", author: "Donald Neamen", price: 840, image: "https://covers.openlibrary.org/b/id/8232064-M.jpg", category: "Engineering" },
  { id: 66, title: "Heat Transfer", author: "Cengel & Ghajar", price: 720, image: "https://covers.openlibrary.org/b/id/8232065-M.jpg", category: "Engineering" },
  { id: 67, title: "Mechanics of Materials", author: "Beer & Johnston", price: 790, image: "https://covers.openlibrary.org/b/id/8232066-M.jpg", category: "Engineering" },
  { id: 68, title: "Soil Mechanics", author: "Braja Das", price: 710, image: "https://covers.openlibrary.org/b/id/8232067-M.jpg", category: "Engineering" },
  { id: 69, title: "Fundamentals of Aerodynamics", author: "John Anderson", price: 860, image: "https://covers.openlibrary.org/b/id/8232068-M.jpg", category: "Engineering" },
  { id: 70, title: "Chemical Engineering Design", author: "Towler & Sinnott", price: 950, image: "https://covers.openlibrary.org/b/id/8232069-M.jpg", category: "Engineering" },
  { id: 71, title: "Digital Electronics", author: "Floyd & Buchla", price: 680, image: "https://covers.openlibrary.org/b/id/8232070-M.jpg", category: "Engineering" },
  { id: 72, title: "Power System Analysis", author: "John Grainger", price: 820, image: "https://covers.openlibrary.org/b/id/8232071-M.jpg", category: "Engineering" },
  { id: 73, title: "Environmental Engineering", author: "Mihelcic & Zimmerman", price: 740, image: "https://covers.openlibrary.org/b/id/8232072-M.jpg", category: "Engineering" },
  { id: 74, title: "Robotics: Modelling and Control", author: "Siciliano et al.", price: 890, image: "https://covers.openlibrary.org/b/id/8232073-M.jpg", category: "Engineering" },
  { id: 75, title: "VLSI Design", author: "Neil Weste", price: 860, image: "https://covers.openlibrary.org/b/id/8232074-M.jpg", category: "Engineering" },
  { id: 76, title: "Manufacturing Engineering", author: "Kalpakjian", price: 910, image: "https://covers.openlibrary.org/b/id/8232075-M.jpg", category: "Engineering" },
  { id: 77, title: "Engineering Drawing", author: "N.D. Bhatt", price: 420, image: "https://covers.openlibrary.org/b/id/8232076-M.jpg", category: "Engineering" },
  { id: 78, title: "Finite Element Method", author: "Zienkiewicz", price: 980, image: "https://covers.openlibrary.org/b/id/8232077-M.jpg", category: "Engineering" },
  { id: 79, title: "Industrial Engineering", author: "Groover", price: 870, image: "https://covers.openlibrary.org/b/id/8232078-M.jpg", category: "Engineering" },
  { id: 80, title: "Numerical Methods for Engineers", author: "Chapra & Canale", price: 750, image: "https://covers.openlibrary.org/b/id/8232079-M.jpg", category: "Engineering" },

  // ── DATA SCIENCE (28 books) ─────────────────────────────
  { id: 17, title: "Data Science from Scratch", author: "Joel Grus", price: 499, image: "https://covers.openlibrary.org/b/id/8232012-M.jpg", category: "Data Science" },
  { id: 18, title: "Hands-On Machine Learning", author: "Aurélien Géron", price: 799, image: "https://covers.openlibrary.org/b/id/8232013-M.jpg", category: "Data Science" },
  { id: 19, title: "Python for Data Analysis", author: "Wes McKinney", price: 649, image: "https://covers.openlibrary.org/b/id/8232014-M.jpg", category: "Data Science" },
  { id: 20, title: "Deep Learning", author: "Ian Goodfellow", price: 899, image: "https://covers.openlibrary.org/b/id/8232015-M.jpg", category: "Data Science" },
  { id: 21, title: "Statistics for Data Science", author: "Peter Bruce", price: 549, image: "https://covers.openlibrary.org/b/id/8232016-M.jpg", category: "Data Science" },
  { id: 22, title: "Feature Engineering", author: "Alice Zheng", price: 499, image: "https://covers.openlibrary.org/b/id/8232017-M.jpg", category: "Data Science" },
  { id: 23, title: "Natural Language Processing", author: "Nitin Hardeniya", price: 579, image: "https://covers.openlibrary.org/b/id/8232018-M.jpg", category: "Data Science" },
  { id: 24, title: "Pattern Recognition", author: "Christopher Bishop", price: 749, image: "https://covers.openlibrary.org/b/id/8232019-M.jpg", category: "Data Science" },
  { id: 81, title: "The Elements of Statistical Learning", author: "Hastie & Tibshirani", price: 899, image: "https://covers.openlibrary.org/b/id/8232080-M.jpg", category: "Data Science" },
  { id: 82, title: "Probabilistic Graphical Models", author: "Daphne Koller", price: 999, image: "https://covers.openlibrary.org/b/id/8232081-M.jpg", category: "Data Science" },
  { id: 83, title: "Data Mining: Concepts and Techniques", author: "Han & Kamber", price: 799, image: "https://covers.openlibrary.org/b/id/8232082-M.jpg", category: "Data Science" },
  { id: 84, title: "Reinforcement Learning", author: "Sutton & Barto", price: 849, image: "https://covers.openlibrary.org/b/id/8232083-M.jpg", category: "Data Science" },
  { id: 85, title: "Applied Predictive Modeling", author: "Kuhn & Johnson", price: 749, image: "https://covers.openlibrary.org/b/id/8232084-M.jpg", category: "Data Science" },
  { id: 86, title: "Big Data: A Revolution", author: "Viktor Mayer-Schönberger", price: 449, image: "https://covers.openlibrary.org/b/id/8232085-M.jpg", category: "Data Science" },
  { id: 87, title: "SQL for Data Scientists", author: "Renee Teate", price: 499, image: "https://covers.openlibrary.org/b/id/8232086-M.jpg", category: "Data Science" },
  { id: 88, title: "Practical Statistics for DS", author: "Bruce & Gedeck", price: 599, image: "https://covers.openlibrary.org/b/id/8232087-M.jpg", category: "Data Science" },
  { id: 89, title: "Data Visualization", author: "Kieran Healy", price: 549, image: "https://covers.openlibrary.org/b/id/8232088-M.jpg", category: "Data Science" },
  { id: 90, title: "Time Series Analysis", author: "Hamilton", price: 899, image: "https://covers.openlibrary.org/b/id/8232089-M.jpg", category: "Data Science" },
  { id: 91, title: "Storytelling with Data", author: "Cole Knaflic", price: 449, image: "https://covers.openlibrary.org/b/id/8232090-M.jpg", category: "Data Science" },
  { id: 92, title: "R for Data Science", author: "Hadley Wickham", price: 549, image: "https://covers.openlibrary.org/b/id/8232091-M.jpg", category: "Data Science" },
  { id: 93, title: "Bayesian Methods for Hackers", author: "Cam Davidson-Pilon", price: 599, image: "https://covers.openlibrary.org/b/id/8232092-M.jpg", category: "Data Science" },
  { id: 94, title: "Spark: The Definitive Guide", author: "Chambers & Zaharia", price: 799, image: "https://covers.openlibrary.org/b/id/8232093-M.jpg", category: "Data Science" },
  { id: 95, title: "Designing Data-Intensive Apps", author: "Martin Kleppmann", price: 849, image: "https://covers.openlibrary.org/b/id/8232094-M.jpg", category: "Data Science" },
  { id: 96, title: "Machine Learning Yearning", author: "Andrew Ng", price: 399, image: "https://covers.openlibrary.org/b/id/8232095-M.jpg", category: "Data Science" },
  { id: 97, title: "Computer Vision", author: "Szeliski", price: 899, image: "https://covers.openlibrary.org/b/id/8232096-M.jpg", category: "Data Science" },
  { id: 98, title: "Speech and Language Processing", author: "Jurafsky & Martin", price: 849, image: "https://covers.openlibrary.org/b/id/8232097-M.jpg", category: "Data Science" },
  { id: 99, title: "AI: A Modern Approach", author: "Russell & Norvig", price: 999, image: "https://covers.openlibrary.org/b/id/8232098-M.jpg", category: "Data Science" },
  { id: 100, title: "Grokking Machine Learning", author: "Luis Serrano", price: 549, image: "https://covers.openlibrary.org/b/id/8232099-M.jpg", category: "Data Science" },

  // ── BUSINESS (28 books) ─────────────────────────────────
  { id: 25, title: "Zero to One", author: "Peter Thiel", price: 399, image: "https://covers.openlibrary.org/b/id/8232020-M.jpg", category: "Business" },
  { id: 26, title: "Good to Great", author: "Jim Collins", price: 449, image: "https://covers.openlibrary.org/b/id/8232021-M.jpg", category: "Business" },
  { id: 27, title: "The Lean Startup", author: "Eric Ries", price: 379, image: "https://covers.openlibrary.org/b/id/8232022-M.jpg", category: "Business" },
  { id: 28, title: "Atomic Habits", author: "James Clear", price: 349, image: "https://covers.openlibrary.org/b/id/8232023-M.jpg", category: "Business" },
  { id: 29, title: "Start with Why", author: "Simon Sinek", price: 329, image: "https://covers.openlibrary.org/b/id/8232024-M.jpg", category: "Business" },
  { id: 30, title: "Deep Work", author: "Cal Newport", price: 369, image: "https://covers.openlibrary.org/b/id/8232025-M.jpg", category: "Business" },
  { id: 31, title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", price: 299, image: "https://covers.openlibrary.org/b/id/8232026-M.jpg", category: "Business" },
  { id: 32, title: "Built to Last", author: "Jim Collins", price: 419, image: "https://covers.openlibrary.org/b/id/8232027-M.jpg", category: "Business" },
  { id: 101, title: "The Hard Thing About Hard Things", author: "Ben Horowitz", price: 399, image: "https://covers.openlibrary.org/b/id/8232100-M.jpg", category: "Business" },
  { id: 102, title: "Thinking, Fast and Slow", author: "Daniel Kahneman", price: 449, image: "https://covers.openlibrary.org/b/id/8232101-M.jpg", category: "Business" },
  { id: 103, title: "The Innovators Dilemma", author: "Clayton Christensen", price: 429, image: "https://covers.openlibrary.org/b/id/8232102-M.jpg", category: "Business" },
  { id: 104, title: "Influence: Psychology of Persuasion", author: "Robert Cialdini", price: 369, image: "https://covers.openlibrary.org/b/id/8232103-M.jpg", category: "Business" },
  { id: 105, title: "The 4-Hour Workweek", author: "Timothy Ferriss", price: 349, image: "https://covers.openlibrary.org/b/id/8232104-M.jpg", category: "Business" },
  { id: 106, title: "Crossing the Chasm", author: "Geoffrey Moore", price: 399, image: "https://covers.openlibrary.org/b/id/8232105-M.jpg", category: "Business" },
  { id: 107, title: "The E-Myth Revisited", author: "Michael Gerber", price: 329, image: "https://covers.openlibrary.org/b/id/8232106-M.jpg", category: "Business" },
  { id: 108, title: "Purple Cow", author: "Seth Godin", price: 299, image: "https://covers.openlibrary.org/b/id/8232107-M.jpg", category: "Business" },
  { id: 109, title: "The Art of War", author: "Sun Tzu", price: 249, image: "https://covers.openlibrary.org/b/id/8232108-M.jpg", category: "Business" },
  { id: 110, title: "Never Split the Difference", author: "Chris Voss", price: 369, image: "https://covers.openlibrary.org/b/id/8232109-M.jpg", category: "Business" },
  { id: 111, title: "Measure What Matters", author: "John Doerr", price: 419, image: "https://covers.openlibrary.org/b/id/8232110-M.jpg", category: "Business" },
  { id: 112, title: "Rework", author: "Jason Fried", price: 299, image: "https://covers.openlibrary.org/b/id/8232111-M.jpg", category: "Business" },
  { id: 113, title: "The Mom Test", author: "Rob Fitzpatrick", price: 279, image: "https://covers.openlibrary.org/b/id/8232112-M.jpg", category: "Business" },
  { id: 114, title: "Hooked", author: "Nir Eyal", price: 349, image: "https://covers.openlibrary.org/b/id/8232113-M.jpg", category: "Business" },
  { id: 115, title: "Sprint", author: "Jake Knapp", price: 369, image: "https://covers.openlibrary.org/b/id/8232114-M.jpg", category: "Business" },
  { id: 116, title: "Blitzscaling", author: "Reid Hoffman", price: 399, image: "https://covers.openlibrary.org/b/id/8232115-M.jpg", category: "Business" },
  { id: 117, title: "The Startup Playbook", author: "David Kidder", price: 449, image: "https://covers.openlibrary.org/b/id/8232116-M.jpg", category: "Business" },
  { id: 118, title: "Founders at Work", author: "Jessica Livingston", price: 379, image: "https://covers.openlibrary.org/b/id/8232117-M.jpg", category: "Business" },
  { id: 119, title: "High Output Management", author: "Andrew Grove", price: 349, image: "https://covers.openlibrary.org/b/id/8232118-M.jpg", category: "Business" },
  { id: 120, title: "The Effective Executive", author: "Peter Drucker", price: 329, image: "https://covers.openlibrary.org/b/id/8232119-M.jpg", category: "Business" },

  // ── SCIENCE (28 books) ──────────────────────────────────
  { id: 33, title: "A Brief History of Time", author: "Stephen Hawking", price: 349, image: "https://covers.openlibrary.org/b/id/8232028-M.jpg", category: "Science" },
  { id: 34, title: "The Selfish Gene", author: "Richard Dawkins", price: 379, image: "https://covers.openlibrary.org/b/id/8232029-M.jpg", category: "Science" },
  { id: 35, title: "Cosmos", author: "Carl Sagan", price: 399, image: "https://covers.openlibrary.org/b/id/8232030-M.jpg", category: "Science" },
  { id: 36, title: "Sapiens", author: "Yuval Noah Harari", price: 449, image: "https://covers.openlibrary.org/b/id/8232031-M.jpg", category: "Science" },
  { id: 37, title: "The Gene", author: "Siddhartha Mukherjee", price: 499, image: "https://covers.openlibrary.org/b/id/8232032-M.jpg", category: "Science" },
  { id: 38, title: "Astrophysics for People in a Hurry", author: "Neil deGrasse Tyson", price: 299, image: "https://covers.openlibrary.org/b/id/8232033-M.jpg", category: "Science" },
  { id: 39, title: "The Grand Design", author: "Stephen Hawking", price: 369, image: "https://covers.openlibrary.org/b/id/8232034-M.jpg", category: "Science" },
  { id: 40, title: "What is Life?", author: "Erwin Schrodinger", price: 279, image: "https://covers.openlibrary.org/b/id/8232035-M.jpg", category: "Science" },
  { id: 121, title: "The Origin of Species", author: "Charles Darwin", price: 299, image: "https://covers.openlibrary.org/b/id/8232120-M.jpg", category: "Science" },
  { id: 122, title: "Surely You're Joking Mr. Feynman", author: "Richard Feynman", price: 349, image: "https://covers.openlibrary.org/b/id/8232121-M.jpg", category: "Science" },
  { id: 123, title: "The Elegant Universe", author: "Brian Greene", price: 399, image: "https://covers.openlibrary.org/b/id/8232122-M.jpg", category: "Science" },
  { id: 124, title: "Pale Blue Dot", author: "Carl Sagan", price: 379, image: "https://covers.openlibrary.org/b/id/8232123-M.jpg", category: "Science" },
  { id: 125, title: "The Emperor's New Mind", author: "Roger Penrose", price: 449, image: "https://covers.openlibrary.org/b/id/8232124-M.jpg", category: "Science" },
  { id: 126, title: "Quantum Mechanics", author: "David Griffiths", price: 799, image: "https://covers.openlibrary.org/b/id/8232125-M.jpg", category: "Science" },
  { id: 127, title: "University Physics", author: "Young & Freedman", price: 899, image: "https://covers.openlibrary.org/b/id/8232126-M.jpg", category: "Science" },
  { id: 128, title: "Organic Chemistry", author: "Clayden et al.", price: 849, image: "https://covers.openlibrary.org/b/id/8232127-M.jpg", category: "Science" },
  { id: 129, title: "Molecular Biology of the Cell", author: "Alberts et al.", price: 999, image: "https://covers.openlibrary.org/b/id/8232128-M.jpg", category: "Science" },
  { id: 130, title: "Campbell Biology", author: "Jane Reece", price: 950, image: "https://covers.openlibrary.org/b/id/8232129-M.jpg", category: "Science" },
  { id: 131, title: "The Double Helix", author: "James Watson", price: 329, image: "https://covers.openlibrary.org/b/id/8232130-M.jpg", category: "Science" },
  { id: 132, title: "Black Holes and Time Warps", author: "Kip Thorne", price: 419, image: "https://covers.openlibrary.org/b/id/8232131-M.jpg", category: "Science" },
  { id: 133, title: "The Structure of Scientific Revolutions", author: "Thomas Kuhn", price: 349, image: "https://covers.openlibrary.org/b/id/8232132-M.jpg", category: "Science" },
  { id: 134, title: "Fermat's Last Theorem", author: "Simon Singh", price: 329, image: "https://covers.openlibrary.org/b/id/8232133-M.jpg", category: "Science" },
  { id: 135, title: "The Man Who Knew Infinity", author: "Robert Kanigel", price: 369, image: "https://covers.openlibrary.org/b/id/8232134-M.jpg", category: "Science" },
  { id: 136, title: "Six Easy Pieces", author: "Richard Feynman", price: 299, image: "https://covers.openlibrary.org/b/id/8232135-M.jpg", category: "Science" },
  { id: 137, title: "The Immortal Life of Henrietta Lacks", author: "Rebecca Skloot", price: 359, image: "https://covers.openlibrary.org/b/id/8232136-M.jpg", category: "Science" },
  { id: 138, title: "Genome", author: "Matt Ridley", price: 349, image: "https://covers.openlibrary.org/b/id/8232137-M.jpg", category: "Science" },
  { id: 139, title: "The Demon-Haunted World", author: "Carl Sagan", price: 379, image: "https://covers.openlibrary.org/b/id/8232138-M.jpg", category: "Science" },
  { id: 140, title: "The Hidden Reality", author: "Brian Greene", price: 399, image: "https://covers.openlibrary.org/b/id/8232139-M.jpg", category: "Science" }
];
